name = "tarotmancer-api"
main = "src/index.js"
compatibility_date = "2026-02-03"

# set these after login or via env
account_id = "7300513683803ba7d754b1b091877a5e"
# workers_dev = true

[vars]
# optional shared secret if you later want a simple auth gate
# API_KEY = ""
